### ISSUE TITLE
how to build a GPU program with Dockefile such as darknet which needs nvcc compile environment

### ISSUE THREAD

**Issue by dqj** [Technica-Corporation/Tegra-Docker#3]
Running a GPU program within a Docker container is right. While i want to build a GPU program, it occurs an error. The error message is:
`make: /usr/local/cuda-9.0/bin/nvcc: Command not found `

**Comment by kgdad** [comment]
If you are trying to compile from within your container, you'll either need to install the TX-2 CUDA packages in your Docker container or if you have CUDA already installed on your device, you can share those files with your container by adding /usr/local/cuda as a volume.

**Comment by Shrunoti** [comment]
Hi, 
I wanted to ask if this worked for @dqj . Because I tried mounting /usr/local/cuda and /usr/local/cuda-9.0 , 
but I get following error after running deviceQuery -
  ```
CUDA driver version is insufficient for CUDA runtime version
Result = FAIL
```

Also running darknet gives me following error- 
`error while loading shared libraries: libcudart.so.9.0: cannot open shared object file: No such file or directory.`

Note that cuda on the host machine runs fine and is compatible with the nvidia drivers.
